apiVersion: v1
kind: ServiceAccount
metadata:
  name: whereami-ksa
  #namespace: whereami
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whereami
  #namespace: whereami
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whereami
  template:
    metadata:
      labels:
        app: whereami
        version: v1
    spec:
      serviceAccountName: whereami-ksa
      containers:
      - name: whereami
        image: gcr.io/alexmattson-scratch/gke-whereami@sha256:f583c97d457c2a53e6b25c4d400799bdc9bdf61f7e4e2d6ff8b77e54f68e0aed
        ports:
          - name: http
            containerPort: 8080
        livenessProbe:
          httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
---
  apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "whereami"
    #namespace: "whereami"
  spec:
    ports:
    - port: 80
      targetPort: 8080
      name: http # adding for Istio
    selector:
      app: "whereami"
    type: "LoadBalancer"