apiVersion: apps/v1
kind: Deployment
metadata:
  name: whereami
  namespace: whereami
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whereami
  template:
    metadata:
      labels:
        app: whereami
        version: v1
    spec:
      serviceAccountName: whereami-ksa
      containers:
      - name: whereami
        image: gcr.io/alexmattson-scratch/gke-whereami:21d41ba803d1d60b73702cafb54ea651c7683670
        ports:
          - name: http
            containerPort: 5000
        livenessProbe:
          httpGet:
              path: /healthz
              port: 5000
              scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
---
  apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "whereami"
    namespace: "whereami"
  spec:
    ports:
    - port: 80
      targetPort: 5000
      name: http # adding for Istio
    selector:
      app: "whereami"
    type: "LoadBalancer"